import React, { Component } from 'react'

class MainContent extends Component {
  render() {
    return (
      <div>
        MainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContent
        MainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContent
        MainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContent
        MainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContent
        MainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContent
        MainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContent
        MainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContent
        MainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContentMainContent
      </div>
    )
  }
}

export default MainContent;